import React from 'react';
import type { Strategy } from '../../types';
import { Card } from '../ui/Card';
import { PlatformIcon } from '../icons/PlatformIcons';
import { MARKETING_GOALS } from '../../constants';
import { ShareButtons } from '../ui/ShareButtons';
import { ClipboardCopyButton } from '../ui/ClipboardCopyButton';

interface StrategyListProps {
  strategies: Strategy[];
}

export const StrategyList: React.FC<StrategyListProps> = ({ strategies }) => {
  if (!strategies || strategies.length === 0) {
    return <Card><p>No strategies were generated.</p></Card>;
  }
  
  const formatStrategyForSharing = (strategy: Strategy): string => {
    const goalLabel = MARKETING_GOALS.find(g => g.id === strategy.goal)?.label || strategy.goal;
    const platformLabel = strategy.platform.replace('_', ' ');
    const recommendationsText = strategy.recommendations.slice(0, 2).map(r => `• ${r}`).join('\n');

    return `🚀 AI-generated marketing strategy for ${platformLabel} to drive ${goalLabel}!\n\n"${strategy.strategy_title}"\n\nTop recommendations:\n${recommendationsText}\n...\n\nCheck out the full plan generated by AI Marketing Agent.`;
  };
  
  const formatStrategyForClipboard = (strategy: Strategy): string => {
    const goalLabel = MARKETING_GOALS.find(g => g.id === strategy.goal)?.label || strategy.goal;
    const platformLabel = strategy.platform.replace('_', ' ');
    const recommendationsText = strategy.recommendations.map(r => `- ${r}`).join('\n');
    const kpisText = strategy.kpis.map(k => `- ${k}`).join('\n');

    return `Marketing Strategy
---
Goal: ${goalLabel}
Platform: ${platformLabel}
---
Title: ${strategy.strategy_title}
Summary: ${strategy.summary}

Recommendations:
${recommendationsText}

Rationale:
${strategy.rationale}

KPIs to Monitor:
${kpisText}
`;
  };

  return (
    <div className="space-y-6">
      {strategies.map((s, i) => (
        <Card key={i} id={`strategy-${i}`}>
          <div className="flex justify-between items-start mb-3">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <PlatformIcon platform={s.platform} />
                <span className="text-sm font-semibold text-neutral uppercase tracking-wider">{s.platform.replace('_', ' ')}</span>
              </div>
              <p className="text-xs text-secondary font-bold">{MARKETING_GOALS.find(g => g.id === s.goal)?.label}</p>
            </div>
            <div className="text-right">
              <p className="text-sm font-semibold">KPIs to watch:</p>
              <div className="flex flex-wrap gap-2 justify-end mt-1">
                {s.kpis.map((kpi) => (
                  <span key={kpi} className="text-xs bg-secondary text-secondary-foreground font-medium px-2 py-1 rounded-full">{kpi.toUpperCase()}</span>
                ))}
              </div>
            </div>
          </div>
          <h3 className="text-xl font-bold text-primary-dark mb-2">{s.strategy_title}</h3>
          <p className="text-neutral mb-4">{s.summary}</p>

          <div className="mb-4">
            <h4 className="font-semibold mb-2 text-neutral-dark">Recommendations:</h4>
            <ul className="list-disc list-inside space-y-1 text-neutral">
              {s.recommendations.map((rec, j) => (
                <li key={j}>{rec}</li>
              ))}
            </ul>
          </div>
          <div className="mb-4">
            <h4 className="font-semibold text-foreground">Rationale:</h4>
            <p className="text-sm text-foreground bg-muted p-3 rounded-lg mt-2">{s.rationale}</p>
          </div>
          <div className="border-t pt-4 mt-4 flex justify-end items-center gap-4">
            <ClipboardCopyButton textToCopy={formatStrategyForClipboard(s)} />
            <ShareButtons textToShare={formatStrategyForSharing(s)} anchorId={`strategy-${i}`} />
          </div>
        </Card>
      ))}
    </div>
  );
};
