import React from 'react';
import type { Strategy } from '../../types';
import { Card } from '../ui/Card';
import { PlatformIcon } from '../icons/PlatformIcons';
import { MARKETING_GOALS } from '../../constants';
import { ShareButtons } from '../ui/ShareButtons';

interface StrategyListProps {
  strategies: Strategy[];
  implementedStrategies: Set<number>;
  onToggleImplemented: (index: number) => void;
}

export const StrategyList: React.FC<StrategyListProps> = ({ strategies, implementedStrategies, onToggleImplemented }) => {
  if (!strategies || strategies.length === 0) {
    return <Card><p>No strategies were generated.</p></Card>;
  }
  
  // Debug logging
  console.log('StrategyList - strategies:', strategies);
  strategies.forEach((s, i) => {
    console.log(`Strategy ${i} - KPIs:`, s.kpis);
    console.log(`Strategy ${i} - Rationale:`, s.rationale);
  });
  
  const formatStrategyForSharing = (strategy: Strategy): string => {
    const goalLabel = MARKETING_GOALS.find(g => g.id === strategy.goal)?.label || strategy.goal;
    const platformLabel = strategy.platform.replace('_', ' ');
    const targetingText = strategy.targeting_suggestions.slice(0, 1).map(r => `• Targeting: ${r}`).join('\n');
    const creativeText = strategy.creative_asset_ideas.slice(0, 1).map(r => `• Creative: ${r}`).join('\n');

    return `🚀 AI-generated marketing strategy for ${platformLabel} to drive ${goalLabel}!\n\n"${strategy.strategy_title}"\n\nKey Insights:\n${targetingText}\n${creativeText}\n...\n\nGenerated by AI Marketing Agent.`;
  };

  return (
    <div className="space-y-6">
      {strategies.map((s, i) => {
        const isImplemented = implementedStrategies.has(i);
        return (
        <Card key={i} className={isImplemented ? 'border-2 border-green-500 bg-green-50' : ''}>
          <div className="flex justify-between items-start mb-3">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <PlatformIcon platform={s.platform} />
                <span className="text-sm font-semibold text-neutral uppercase tracking-wider">{s.platform.replace('_', ' ')}</span>
              </div>
              <p className="text-xs text-secondary font-bold">{MARKETING_GOALS.find(g => g.id === s.goal)?.label}</p>
            </div>
            <div className="text-right">
              <p className="text-sm font-bold text-neutral-dark mb-2">KPIs to watch:</p>
              <div className="flex flex-wrap gap-2 justify-end">
                {s.kpis && s.kpis.length > 0 ? (
                  s.kpis.map((kpi) => (
                    <span key={kpi} className="text-xs bg-accent text-white font-bold px-3 py-1.5 rounded-full shadow-sm uppercase tracking-wide">
                      {kpi}
                    </span>
                  ))
                ) : (
                  <span className="text-xs text-neutral italic">No KPIs specified</span>
                )}
              </div>
            </div>
          </div>
          <h3 className="text-xl font-bold text-neutral-dark mb-2">{s.strategy_title}</h3>
          <p className="text-neutral mb-4 leading-relaxed">{s.summary}</p>
          
          <div className="mb-4">
            <h4 className="font-semibold mb-2 text-neutral-dark">Recommendations:</h4>
            <ul className="list-disc list-inside space-y-2 text-neutral">
              {s.recommendations.map((rec, j) => (
                <li key={j} className="leading-relaxed">{rec}</li>
              ))}
            </ul>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6 pt-4 border-t border-neutral-light">
            <div>
                <h4 className="font-semibold mb-3 text-neutral-dark">Targeting Suggestions:</h4>
                <ul className="list-disc list-inside space-y-2 text-sm text-neutral">
                    {s.targeting_suggestions.map((rec, j) => (
                        <li key={j} className="leading-relaxed">{rec}</li>
                    ))}
                </ul>
            </div>
            <div>
                <h4 className="font-semibold mb-3 text-neutral-dark">Creative Asset Ideas:</h4>
                <ul className="list-disc list-inside space-y-2 text-sm text-neutral">
                    {s.creative_asset_ideas.map((rec, j) => (
                        <li key={j} className="leading-relaxed">{rec}</li>
                    ))}
                </ul>
            </div>
          </div>
          
          {s.budget_allocation && s.budget_allocation.length > 0 && (
            <div className="mt-6 pt-4 border-t border-neutral-light">
                <h4 className="font-semibold mb-3 text-neutral-dark">Budget Allocation:</h4>
                <div className="space-y-3">
                    {s.budget_allocation.map((alloc, j) => (
                        <div key={j} className="p-4 bg-primary-light/10 rounded-lg border border-primary-light/30">
                            <div className="flex justify-between items-center font-semibold text-sm mb-2">
                                <span className="text-neutral-dark">{alloc.category}</span>
                                <span className="text-primary text-lg">{alloc.percentage}%</span>
                            </div>
                            <p className="text-xs text-neutral leading-relaxed">{alloc.rationale}</p>
                        </div>
                    ))}
                </div>
            </div>
          )}

          <div className="mt-6 pt-4 border-t border-neutral-light bg-primary-light/5 -mx-4 px-4 pb-4 rounded-lg">
            <h4 className="font-bold text-lg text-neutral-dark mb-3 mt-4">Rationale:</h4>
            <div className="text-base text-neutral-dark bg-white p-4 rounded-lg leading-relaxed border-2 border-primary-light/30 shadow-sm">
              {s.rationale || 'No rationale provided'}
            </div>
          </div>

          <div className="border-t pt-4 mt-4 flex justify-between items-center">
             <button
                onClick={() => onToggleImplemented(i)}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-colors ${
                    isImplemented
                    ? 'bg-green-100 text-green-800 hover:bg-green-200'
                    : 'bg-gray-200 text-gray-800 hover:bg-gray-300'
                }`}
            >
                {isImplemented ? (
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                ) : (
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                )}
                {isImplemented ? 'Implemented' : 'Mark as Implemented'}
            </button>
            <ShareButtons textToShare={formatStrategyForSharing(s)} />
          </div>
        </Card>
      )})}
    </div>
  );
};
